# Generated by Django 2.2.2 on 2021-11-15 12:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemManage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uselanguage', models.TextField(choices=[('java', 'java'), ('python', 'python'), ('html', 'html')], verbose_name='使用言語')),
                ('usesyntax', models.TextField(choices=[('for', 'for')], verbose_name='使用構文')),
                ('usesyntaxtext', models.CharField(max_length=10, verbose_name='その他の構文')),
                ('problemstate', models.CharField(max_length=40, verbose_name='問題文')),
                ('problemimage', models.ImageField(blank=True, null=True, upload_to='', verbose_name='問題文画像')),
                ('difficulty', models.TextField(choices=[('初級', '初級'), ('中級', '中級'), ('上級', '上級')], verbose_name='難易度')),
                ('tips', models.TextField(blank=True, null=True, verbose_name='ヒント')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name_plural': 'ProblemManage',
            },
        ),
    ]
